name: React Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull main branch
        run: git pull origin main

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Restart Nginx on EC2
        run: |
          sudo systemctl restart nginx
